kind: Securesign
apiVersion: rhtas.redhat.com/v1alpha1
metadata:
  annotations:
    rhtas.redhat.com/metrics: 'true'
  labels:
    app.kubernetes.io/instance: {{INSTANCE_NAME}}
    app.kubernetes.io/name: {{INSTANCE_NAME}}
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: {{INSTANCE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  ctlog:
    monitoring:
      enabled: true
  fulcio:
    certificate:
      commonName: fulcio.hostname
      organizationEmail: jdoe@redhat.com
      organizationName: Red Hat
    config:
      OIDCIssuers:
        - ClientID: trusted-artifact-signer
          Issuer: 'https://your-oidc-issuer-url'
          IssuerURL: 'https://your-oidc-issuer-url'
          Type: email
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
  rekor:
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
  trillian:
    database:
      create: true
    monitoring:
      enabled: true
  tsa:
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
    ntpMonitoring:
      enabled: true
    signer:
      certificateChain:
        intermediateCA:
          - commonName: tsa.hostname-intermediate
            organizationEmail: jdoe@redhat.com
            organizationName: Red Hat
        leafCA:
          commonName: tsa.hostname-leaf
          organizationEmail: jdoe@redhat.com
          organizationName: Red Hat
        rootCA:
          commonName: tsa.hostname-root
          organizationEmail: jdoe@redhat.com
          organizationName: Red Hat
  tuf:
    externalAccess:
      enabled: true
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
      - name: tsa.certchain.pem
    pvc:
      accessModes:
        - ReadWriteOnce
      retain: true
      size: 100Mi
    rootKeySecretRef:
      name: tuf-root-keys
