kind: CTlog
apiVersion: rhtas.redhat.com/v1alpha1
metadata:
  labels:
    app.kubernetes.io/instance: {{INSTANCE_NAME}}
    app.kubernetes.io/name: {{INSTANCE_NAME}}
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: {{INSTANCE_NAME}}
  namespace: {{NAMESPACE}}
spec: {}
